### ISSUE TITLE
Effective Python

### ISSUE THREAD

**Issue by intptr-t** [aosn/aosn.github.io#12]
#### (1) タイトル

Effective Python――Pythonプログラムを改良する59項目

#### (2) 著者・訳者

* Brett Slatkin (著)
* 黒川 利明 (訳)
* 石本 敦夫　(監)

#### (3) ページ数

272

#### (4) 出版日 (yyyy/MM/dd)

2016/1/23

#### (5) 出版社

O'Reilly Japan

#### (6) フォーマット

- [x] 紙
- [ ] EPUB・AZW・MOBI
- [x] PDF

#### (7) ISBN

978-4-87311-761-4

#### (8) ウェブサイト (出版社ページまたは Amazon)

https://www.oreilly.co.jp/books/9784873117560/
https://www.amazon.co.jp/dp/4873117569

#### (1) 推薦理由

PythonはLinuxのスクリプト、機械学習、Web向けフレームワークなど幅広く応用されている。
しかしマルチパラダイム・動的型付けの言語であり、いろいろな書き方出来るメリットがある反面、速度低下を招くデメリットなどもある。
良い書き方の学習、こんな(良い/悪い)書き方ができるなどの議論できればよいと考えています。
~~(読みたいと思って買ったが、積本と化したいるから)~~

#### (2) 運営協力

- [ ] 司会進行に立候補する (本書が選出された場合)

### 提案者チェック欄

- [x] 出版日が1年以内であることを確認しました (Aパート提案の場合は原則必須)
- [x] チケットを自分 (提案者) にアサインしました (必須)
- [x] ラベル「Aパート提案」「Bパート提案」「Cパート提案」を設定しました (複数選択可)

**Comment by mikan** [comment]
Result of 9th Book Poll (Source: [Mosaic](http://vote.tasktoys.com/#!result/1))

| Rank | Ticket | Title | Votes |
| --: | :-: | :-- | :-- |
| 1 | #7 | ブロックチェーン 仕組みと理論 | :+1::+1::+1::+1::+1::+1::+1::+1::+1: |
| 2 | #12 | Effective Python――Pythonプログラムを改良する59項目 | :+1::+1::+1::+1::+1::+1: |
| 3 | #10 | Slack入門 | :+1::+1::+1: |
| 4 | #11 | PythonによるWebスクレイピング | :+1::+1: |

(2 votes per person, total 10 persons)

This ticket is still open for next poll.

**Comment by mikan** [comment]
出版日が1年を超えAパートの投票対象外となったため本提案は Close します。
Aパート以外で再提案することは引き続き可能です。その場合は本提案を Reopen し、適切な Label を付与してください。
