### ISSUE TITLE
C++によるプログラミングの原則と実践 

### ISSUE THREAD

**Issue by MrBearing** [aosn/aosn.github.io#17]
#### (1) タイトル
C++によるプログラミングの原則と実践 
#### (2) 著者・訳者
Bjarne Stroustrup (著), 江添 亮 (監修), 株式会社クイープ/遠藤美代子 (その他)
#### (3) ページ数
1248ページ
#### (4) 出版日 (yyyy/MM/dd)
 2016/9/2
#### (5) 出版社
KADOKAWA
#### (6) フォーマット
 - [x] 紙
 - [x] EPUB・AZW・MOBI  (kindleのみ) 
 - [ ] PDF

#### (7) ISBN
ISBN-10: 4048930516
ISBN-13: 978-4048930512
#### (8) ウェブサイト (出版社ページまたは Amazon)
https://www.amazon.co.jp/dp/4048930516/

#### (1) 推薦理由
c++ 11/14が各種コンパイラにも実装され、皆様も状況によってはc++でのプログラミング可能性は無きにしもあらずであると思います。ラムダ式の実装や、各種スマートポインタ等のモダンな機能を実装したc++にぜひともチャレンジしてみたいため、起票します。

#### (2) 運営協力

- [ ] 司会進行に立候補する (本書が選出された場合)

### 提案者チェック欄

- [x] 出版日が1年以内であることを確認しました (Aパートの場合は原則必須)
- [x] チケットを自分 (提案者) にアサインしました (必須)
- [x] ラベル「Aパート提案」「Bパート提案」「Cパート提案」を設定しました (複数選択可)

**Comment by mikan** [comment]
Result of 10th Book Poll (Source: [1st Poll](http://vote.tasktoys.com/#!result/2), [Runoff](http://vote.tasktoys.com/#!result/3), [Runoff 2](http://vote.tasktoys.com/#!result/3))

|Rank|Ticket| Title                               | 1st Poll         | Runoff | Runoff 2 |
|---:|:----:|:------------------------------------|:-----------------|:-------|:---------|
| 1  | #21  | **プログラミングElixir**             | :+1::+1::+1::+1: | 4      | 6        |
| 2  | #20  | 確率的グラフィカルモデル              | :+1::+1::+1::+1: | 4      | 3        |
| 3  | #19  | 言語のしくみ                         | :+1::+1::+1::+1: | 1      | -        |
| 4  | #10  | Slack入門                           | :+1::+1::+1:     | -      | -        |
| 5  | #18  | スケーラブルリアルタイムデータ分析入門 | :+1:            | -      | -        |
| 5  | #17  | C++によるプログラミングの原則と実践   | :+1:             | -      | -         |
| 5  | #11  | PythonによるWebスクレイピング        | :+1:             | -      | -         |

(2 votes per person, total 9 persons)

This ticket is still open for next poll.
