### ISSUE TITLE
確率的グラフィカルモデル

### ISSUE THREAD

**Issue by kzt-ysmr** [aosn/aosn.github.io#20]
### 書籍情報
ビッグデータ解析の時代に最も注目されている手法の一つが,因果モデル解析,未知データの予測など多くの用途に用いられる「確率的グラフィカルモデル」である。確率的グラフィカルモデルとは,グラフによりモデルを視覚的に記述することができ,また古典的なデータ解析手法のほとんどがその下位モデルとなる最先端手法であり,今後ますますその需要は大きくなるであろう。
本書は,ベイジアンネットワーク,因果推論,離散論理によるグラフィカルモデル,統計力学とグラフィカルモデル,グラフィカルモデルの産業への応用を,それぞれの分野で世界的に活躍する気鋭の研究者たちがわかりやすく解説する。

#### (1) タイトル
確率的グラフィカルモデル

#### (2) 著者・訳者
鈴木 譲 (著, 編集), 植野 真臣 (著, 編集), 黒木 学 (著), 清水 昌平 (著), 湊 真一 (著), 石畠 正和 (著), 樺島 祥介 (著), 田中 和之 (著), 本村 陽一 (著), 玉田 嘉紀 (著)

#### (3) ページ数
292ページ

#### (4) 出版日 (yyyy/MM/dd)
2016/7/23

#### (5) 出版社
共立出版

#### (6) フォーマット

- [x] 紙
- [ ] EPUB・AZW・MOBI
- [ ] PDF

#### (7) ISBN13
978-4320111394

#### (8) ウェブサイト (出版社ページまたは Amazon)
https://www.amazon.co.jp/%E7%A2%BA%E7%8E%87%E7%9A%84%E3%82%B0%E3%83%A9%E3%83%95%E3%82%A3%E3%82%AB%E3%83%AB%E3%83%A2%E3%83%87%E3%83%AB-%E9%88%B4%E6%9C%A8-%E8%AD%B2/dp/4320111397/ref=pd_rhf_dp_s_cp_7?_encoding=UTF8&pd_rd_i=4320111397&pd_rd_r=TA60P7P2BA9GXH9MBY5W&pd_rd_w=9uwGU&pd_rd_wg=Re8Uj&psc=1&refRID=TA60P7P2BA9GXH9MBY5W

### 提案内容
Aパートで読みたい。演習など不足に思われる場合は、自分たちで課題を設定し小規模の開発をすることなども視野に入れ読み進めたい。

#### (1) 推薦理由
* マーケティングやユーザ相関関係分析などビッグデータ解析や機械学習を本当に使いたい実務上の局面において、背後にある現象のメカニズムは必ずしも既知ではありません。複合的要因の分析から因果関係解明へのステップは多くの場合困難を伴うでしょう。Apache Sparkなど強力な道具を使いこなすためにも、結局のところ、統計手法を理解し適切なモデリングができるか否かが極めて重要な鍵と考えます。
* 提案本はベイジアンネットワークをはじめとする確率的グラフィカルモデルについてまとめています。ビッグデータ解析の文脈で注目される汎用的パラダイムである確率的グラフィカルモデルについて学習し、実務につなげられる水準の統計解析・機械学習スキルを目指せればと思い提案しました。

#### (2) 運営協力

- [ ] 司会進行に立候補する (本書が選出された場合)

### 提案者チェック欄

- [x] チケットを自分 (提案者) にアサインしました (必須)
- [x] 運営ポリシーを確認しました https://aosn.github.io/policy (必須)
- [x] ラベル「Aパート提案」「Bパート提案」「Cパート提案」を設定しました (複数設定可)
- [x] *(Aパートの場合のみ)* 出版日が1年以内であることを確認しました

**Comment by kzt-ysmr** [comment]
トピックは面白いし応用事例など参考にはなりそうだが，1冊で基礎から理解できる構成ではない．文章的・数学的にも粗が目立つ．読書会には不向きでした．

**Comment by kzt-ysmr** [comment]
投票対象としては残すことになりました．

**Comment by mikan** [comment]
Result of 10th Book Poll (Source: [1st Poll](http://vote.tasktoys.com/#!result/2), [Runoff](http://vote.tasktoys.com/#!result/3), [Runoff 2](http://vote.tasktoys.com/#!result/3))

|Rank|Ticket| Title                               | 1st Poll         | Runoff | Runoff 2 |
|---:|:----:|:------------------------------------|:-----------------|:-------|:---------|
| 1  | #21  | **プログラミングElixir**             | :+1::+1::+1::+1: | 4      | 6        |
| 2  | #20  | 確率的グラフィカルモデル              | :+1::+1::+1::+1: | 4      | 3        |
| 3  | #19  | 言語のしくみ                         | :+1::+1::+1::+1: | 1      | -        |
| 4  | #10  | Slack入門                           | :+1::+1::+1:     | -      | -        |
| 5  | #18  | スケーラブルリアルタイムデータ分析入門 | :+1:            | -      | -        |
| 5  | #17  | C++によるプログラミングの原則と実践   | :+1:             | -      | -         |
| 5  | #11  | PythonによるWebスクレイピング        | :+1:             | -      | -         |

(2 votes per person, total 9 persons)

This ticket is still open for next poll.
