### ISSUE TITLE
プログラミングElixir

### ISSUE THREAD

**Issue by n39i** [aosn/aosn.github.io#21]
#### (1) タイトル
プログラミングElixir

#### (2) 著者・訳者
Dave Thomas (著), 笹田耕一 (翻訳), 鳥井 雪 (翻訳)

#### (3) ページ数
360

#### (4) 出版日 (yyyy/MM/dd)
2016-08-19

#### (5) 出版社
オーム社

#### (6) フォーマット

- [x] 紙
- [ ] EPUB・AZW・MOBI
- [ ] PDF
- [x] Kindle

#### (7) ISBN13
978-4274219153

#### (8) ウェブサイト (出版社ページまたは Amazon)
www.amazon.co.jp/dp/4274219151

#### (1) 推薦理由
言語やりたい。丁度Erlang触ってないし折角ならElixir。

#### (2) 運営協力

- [x] 司会進行に立候補する (本書が選出された場合)

### 提案者チェック欄

- [x] チケットを自分 (提案者) にアサインしました (必須)
- [x] 運営ポリシーを確認しました https://aosn.github.io/policy (必須)
- [x] ラベル「Aパート提案」「Bパート提案」「Cパート提案」を設定しました (複数設定可)
- [x] *(Aパートの場合のみ)* 出版日が1年以内であることを確認しました

**Comment by mikan** [comment]
Result of 10th Book Poll (Source: [1st Poll](http://vote.tasktoys.com/#!result/2), [Runoff](http://vote.tasktoys.com/#!result/3), [Runoff 2](http://vote.tasktoys.com/#!result/3))

|Rank|Ticket| Title                               | 1st Poll         | Runoff | Runoff 2 |
|---:|:----:|:------------------------------------|:-----------------|:-------|:---------|
| 1  | #21  | **プログラミングElixir**             | :+1::+1::+1::+1: | 4      | 6        |
| 2  | #20  | 確率的グラフィカルモデル              | :+1::+1::+1::+1: | 4      | 3        |
| 3  | #19  | 言語のしくみ                         | :+1::+1::+1::+1: | 1      | -        |
| 4  | #10  | Slack入門                           | :+1::+1::+1:     | -      | -        |
| 5  | #18  | スケーラブルリアルタイムデータ分析入門 | :+1:            | -      | -        |
| 5  | #17  | C++によるプログラミングの原則と実践   | :+1:             | -      | -         |
| 5  | #11  | PythonによるWebスクレイピング        | :+1:             | -      | -         |

(2 votes per person, total 9 persons)

popularity rate: 44.4% (4/9) in 1st poll, 66.7% (6/9) in runoff 2

This book is WIN!
