### ISSUE TITLE
珠玉のプログラミング

### ISSUE THREAD

**Issue by MrBearing** [aosn/aosn.github.io#35]
#### (1) タイトル
珠玉のプログラミング

#### (2) 著者・訳者
ジョン・ベントリー (著), 小林 健一郎 (翻訳)

#### (3) ページ数
305

#### (4) 出版日
2014/2/28

#### (5) 出版社
丸善出版

#### (6) フォーマット

- [x] 紙
- [ ] EPUB・AZW・MOBI
- [ ] PDF

#### (7) ISBN13
978-4621066072

#### (8) ウェブサイト (出版社ページまたは Amazon)
http://amzn.asia/cvJ5xEC

#### (1) 推薦理由
本書は、エレガントなプログラムを書く際のアドバイスや手法について解説しています。探索やソートデータ構造について、理論的な内容よりも実践的な内容に重点を置いているので、我々のような職業プログラマーにとって非常に有用な書籍となると考え起票しました

#### (2) 運営協力

- [x] 司会進行に立候補する (本書が選出された場合)

### 提案者チェック欄

- [x] チケットを自分 (提案者) にアサインしました (必須)
- [x] 運営ポリシーを確認しました https://aosn.github.io/policy (必須)
- [x] ラベル「Aパート提案」「Bパート提案」を設定しました (複数設定可)
- [ ] ~~*(Aパートの場合のみ)* 出版日が1年以内であることを確認しました~~

**Comment by mikan** [comment]
@MrBearing 推薦理由の記載お願いします。あとページ数欄は将来パースすることを想定しているので整数のみにしてください。

**Comment by MrBearing** [comment]
ほい
