### ISSUE TITLE
PythonとJavaScriptではじめるデータビジュアライゼーション

### ISSUE THREAD

**Issue by intptr-t** [aosn/aosn.github.io#37]
#### (1) タイトル

PythonとJavaScriptではじめるデータビジュアライゼーション

#### (2) 著者・訳者

* Kyran Dale 著
* 嶋田 健志 監訳
* 木下 哲也 訳

#### (3) ページ数

500

#### (4) 出版日

2017/08/25

#### (5) 出版社

オライリージャパン

#### (6) フォーマット

- [x] 紙
- [ ] EPUB・AZW・MOBI
- [x] PDF

#### (7) ISBN13

978-4873118086

#### (8) ウェブサイト (出版社ページまたは Amazon)

https://www.oreilly.co.jp/books/9784873118086/
https://www.amazon.co.jp/dp/4873118085

#### (1) 推薦理由

GUIに近い内容を読書会でやっておらず、知見を広げるため
Pythonやりたい

#### (2) 運営協力

- [x] 司会進行に立候補する (本書が選出された場合)

### 提案者チェック欄

- [x] チケットを自分 (提案者) にアサインしました (必須)
- [x] 運営ポリシーを確認しました https://aosn.github.io/policy (必須)
- [x] ラベル「Aパート提案」「Bパート提案」を設定しました (複数設定可)
- [x] *(Aパートの場合のみ)* 出版日が1年以内であることを確認しました

**Comment by mikan** [comment]
期限切れにつきクローズ｀
