### ISSUE TITLE
 プログラミングROS

### ISSUE THREAD

**Issue by MrBearing** [aosn/aosn.github.io#41]
#### (1) タイトル

プログラミングROS

#### (2) 著者・訳者
Morgan Quigley  (著),‎ Brian Gerkey (著),‎ William D. Smart (著),‎ 河田 卓志 (監修),‎ 松田 晃一 (翻訳),‎ 福地 正樹 (翻訳),‎ 由谷 哲夫 (翻訳)

#### (3) ページ数
 480ページ

#### (4) 出版日
2017/12/13

#### (5) 出版社
オライリージャパン 

#### (6) フォーマット

- [x] 紙
- [ ] EPUB・AZW・MOBI
- [ ] PDF

#### (7) ISBN13
978-4873118093

#### (8) ウェブサイト (出版社ページまたは Amazon)
https://www.oreilly.co.jp/books/9784873118093/
 http://amzn.asia/809JANu

#### (1) 推薦理由
ROSはロボットのソフト開発を行う際に極めて重要なツールです。
市販の80のロボットがすでに対応しており、ロボットシステムが容易に構築が可能になるので学んでおいて損はないと思います。

#### (2) 運営協力

- [x] 司会進行に立候補する (本書が選出された場合)

### 提案者チェック欄

- [x] チケットを自分 (提案者) にアサインしました (必須)
- [x] 運営ポリシーを確認しました https://aosn.github.io/policy (必須)
- [x] ラベル「Aパート提案」「Bパート提案」を設定しました (複数設定可)
- [x] *(Aパートの場合のみ)* 出版日が1年以内であることを確認しました

**Comment by mikan** [comment]
@MrBearing チェックボックスを正しく記入してください

`[ x]` -> `[x]`
