### ISSUE TITLE
人月の神話

### ISSUE THREAD

**Issue by akeboshi** [aosn/aosn.github.io#5]
#### (1) タイトル

人月の神話
#### (2) 著者・訳者

Jr FrederickP.Brooks (著), Jr.,Frederick P. Brooks (原著), 滝沢 徹 (翻訳), 牧野 祐子 (翻訳), 富澤 昇 (翻訳)
#### (3) ページ数

321ページ
#### (4) 出版日 (yyyy/MM/dd)

 2014/04/22
#### (5) 出版社

丸善出版
#### (6) フォーマット
- [x] 紙
- [ ] EPUB・AZW・MOBI
- [ ] PDF
#### (7) ISBN

978-4621066089
#### (8) ウェブサイト (出版社ページまたは Amazon)

https://www.amazon.co.jp/dp/4621066080/

#### (1) 推薦理由

歴史的名著を読もう

#### (2) 運営協力

- [ ] 司会進行に立候補する (本書が選出された場合)

### 提案者チェック欄

- [ ] 出版日が1年以内であることを確認しました (Aパート提案の場合は原則必須)
- [x] チケットを自分 (提案者) にアサインしました (必須)
- [x] ラベル「Aパート提案」「Bパート提案」「Cパート提案」を設定しました (複数選択可)

**Comment by mikan** [comment]
Result of 8th Book Election (Source: [Typeform](https://kagaorange.typeform.com/report/lGmHEK/qYoN))

| Rank | Ticket | TItle | Votes |
| --: | :-: | :-- | :-- |
| 1 | #3 | マイクロサービスアーキテクチャ | :+1::+1::+1::+1::+1::+1::+1: |
| 2 | #5 | 人月の神話 | :+1::+1::+1::+1::+1: |
| 3 | #6 | ビジネスモデルの教科書 上級編 | :+1::+1::+1::+1: |
| 4 | #4 | Release It! | :+1::+1: |

(2 votes per person, total 9 persons)

This tiket is still open for next election.
