### ISSUE TITLE
ビジネスモデルの教科書【上級編】

### ISSUE THREAD

**Issue by kzt-ysmr** [aosn/aosn.github.io#6]
#### (1) タイトル

ビジネスモデルの教科書【上級編】
#### (2) 著者・訳者

今枝 昌宏 (著)
#### (3) ページ数

310
#### (4) 出版日 (yyyy/MM/dd)

2016/07/29
#### (5) 出版社

東洋経済新報社
#### (6) フォーマット
- [x] 紙
- [x] EPUB・AZW・MOBI
- [ ] PDF
#### (7) ISBN

ISBN-10: 4492533842
#### (8) ウェブサイト (出版社ページまたは Amazon)

https://www.amazon.co.jp/dp/4492533842/

#### (1) 推薦理由

- 提案者動機： 経営・ソリューション営業・コンサルな人たちの思考回路を知りたい．
- Bパート推薦理由： 議論中心で読んだら楽しそう．参加者各々の視点を活かせそう．

#### (2) 運営協力

- [ ] 司会進行に立候補する (本書が選出された場合)

### 提案者チェック欄

- [ ] 出版日が1年以内であることを確認しました (Aパート提案の場合は原則必須)
- [x] チケットを自分 (提案者) にアサインしました (必須)
- [x] ラベル「Aパート提案」「Bパート提案」「Cパート提案」を設定しました (複数選択可)

**Comment by mikan** [comment]
Result of 8th Book Election (Source: [Typeform](https://kagaorange.typeform.com/report/lGmHEK/qYoN))

| Rank | Ticket | TItle | Votes |
| --: | :-: | :-- | :-- |
| 1 | #3 | マイクロサービスアーキテクチャ | :+1::+1::+1::+1::+1::+1::+1: |
| 2 | #5 | 人月の神話 | :+1::+1::+1::+1::+1: |
| 3 | #6 | ビジネスモデルの教科書 上級編 | :+1::+1::+1::+1: |
| 4 | #4 | Release It! | :+1::+1: |

(2 votes per person, total 9 persons)

This tiket is still open for next election.
